### ISSUE TITLE
Предлагаю помощь

### ISSUE THREAD

**Issue by SeryiBaran** [CyberPotat42/cyberpotato-site#1]
Привет!
Я могу помочь допилить локализацию, комментарии и кнопки поделиться, если нужно.

**Comment by potat-dev** [comment]
Привет! Было бы неплохо, я сейчас сам только начинаю изучать Jekyll, и, если знаешь как улучшить мой сайт, можешь кинуть пулл реквест, я рассмотрю и добавлю изменения!

Комментарии я думаю и сам смогу настроить, локализацию скорее всего так и оставлю английскую, да и кнопки поделиться по умолчанию вроде неплохие. А вот что я хотел бы добавить - это кнопка "Войти как админ" в нижней части сайдбара

**Comment by SeryiBaran** [comment]
>Войти как админ

Хм, а какой функционал будет у этой кнопки?

**Comment by potat-dev** [comment]
Просто переброска пользователя на страницу `/admin`

**Comment by SeryiBaran** [comment]
К сожалению с авторизацией я не работал, помочь не смогу.
